### ISSUE TITLE
Nicer Input Format

### ISSUE THREAD

**Issue by r-barnes** [r-barnes/faster-unmixer#9]
@AlexLipp - our input data is divided between `fitted_samp_locs_no_dupes` and `samples.dat`.

Is this a natural divide on your end? It feels unnatural to handle it in `src/faster-unmixer.cpp` since it could require the user to break up their data if it's in two separate files, so I'd prefer that we require merged data.

Does that seem reasonable to you?

**Comment by AlexLipp** [comment]
Sorry, missed this when first opened. No I think this is an unnatural divide and really just a relict from some (poor) file-management of mine during the early stages of my PhD. In general I think its reasonable to expect an input observation dataset to be in just one file of form:

Sample name | x-coordinate | y-coordinate | element1 | element2 | ... | elementN

**Comment by r-barnes** [comment]
@AlexLipp : I've address this in #25  - could you review?
